### ISSUE TITLE
todos

### ISSUE THREAD

**Issue by Gumball12** [naen-nae/naen-nae#33]
scoring 필요

- [ ] 다양한 기준으로 폰트 정렬될 수 있도록 옵션 제공 (#39)
  - 현재는 제작자 이름으로만 기준으로 정렬되어 있으나, 이를 다양한 기준으로 정렬될 수 있도록 옵션을 제공하면 더욱 좋은 사용자 경험을 얻을 수 있을 것
  - clicks, descending, ascending, random, name
- [ ] 필터링 옵션 (#40)
  - monospaced
- [ ] make `CardBox` horizontal scrollable (#36)
- [ ] 고정폭(monospaced) 확인 가능하게끔 (#35)
- [ ] 검색 시 초성을 이용해 검색 가능하게끔 (#37)
- [x] 부적절한 단어 및 글꼴 제거
- [ ] opencollective -> sponsorship svg hook
- [ ] ga actions (#42)
- [ ] ga policies (#42)
- [x] neo 둥근모, neo 둥근모 pro, neo 둥근모 code 추가
- [ ] remove hash path (#43)
- [ ] `CONTRIBUTION.md` (#38)
- [ ] migrate to ts (#44)
- [ ] fossa, snyk (#38)
