### ISSUE TITLE
revise docs

### ISSUE THREAD

**Issue by Gumball12** [naen-nae/naen-nae#38]
- [x] add `CONTRIBUTION.md` file
- [x] add fossa (related: #52)
- [x] add snyk (related: #53)
- [x] add `FEATURES.md` file
- [x] 왜 이렇게 구성했는지에 대한 내용 (related: #46)
